import "./globals.css";

import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";

import Footer from "@/components/footer";
import { Toaster } from "@/components/ui/sonner";
import { TanstackClientProvider } from "@/providers/tanstack-query";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${plusJakartaSans.variable} antialiased`}>
        <TanstackClientProvider>
          {children}
          <Footer />
          <Toaster />
        </TanstackClientProvider>
      </body>
    </html>
  );
}
